from storage.engine import CollectionStore, NOW
from reo.console.logging import logger

CollectionName = 'antinuke_settings'

_store = CollectionStore(
    name=CollectionName,
    defaults={'enabled': False, 'type': 'normal', 'anti_channel_create': False, 'anti_channel_create_limit': 1, 'anti_channel_create_punishment': 'kick', 'anti_channel_delete': False, 'anti_channel_delete_limit': 1, 'anti_channel_delete_punishment': 'kick', 'anti_channel_update': False, 'anti_channel_update_limit': 1, 'anti_channel_update_punishment': 'kick', 'anti_role_create': False, 'anti_role_create_limit': 1, 'anti_role_create_punishment': 'kick', 'anti_role_delete': False, 'anti_role_delete_limit': 1, 'anti_role_delete_punishment': 'kick', 'anti_role_update': False, 'anti_role_update_limit': 1, 'anti_role_update_punishment': 'kick', 'anti_member_ban': False, 'anti_member_ban_limit': 1, 'anti_member_ban_punishment': 'kick', 'anti_member_unban': False, 'anti_member_unban_limit': 1, 'anti_member_unban_punishment': 'kick', 'anti_member_kick': False, 'anti_member_kick_limit': 1, 'anti_member_kick_punishment': 'kick', 'anti_member_update': False, 'anti_member_update_limit': 1, 'anti_member_update_punishment': 'kick', 'anti_bot_add': False, 'anti_bot_add_limit': 1, 'anti_bot_add_punishment': 'kick', 'anti_invite_delete': False, 'anti_invite_delete_limit': 1, 'anti_invite_delete_punishment': 'kick', 'anti_webhook_create': False, 'anti_webhook_create_limit': 1, 'anti_webhook_create_punishment': 'kick', 'anti_webhook_delete': False, 'anti_webhook_delete_limit': 1, 'anti_webhook_delete_punishment': 'kick', 'anti_webhook_update': False, 'anti_webhook_update_limit': 1, 'anti_webhook_update_punishment': 'kick', 'anti_server_update': False, 'anti_server_update_limit': 1, 'anti_server_update_punishment': 'kick', 'anti_emote_create': False, 'anti_emote_create_limit': 1, 'anti_emote_create_punishment': 'kick', 'anti_emote_delete': False, 'anti_emote_delete_limit': 1, 'anti_emote_delete_punishment': 'kick', 'anti_emote_update': False, 'anti_emote_update_limit': 1, 'anti_emote_update_punishment': 'kick', 'anti_prune_member': False, 'anti_prune_member_limit': 1, 'anti_prune_member_punishment': 'kick', 'anti_everyone_mention': False, 'anti_everyone_mention_limit': 1, 'anti_everyone_mention_punishment': 'mute', 'created_at': NOW},
    unique_sets=[['guild_id']],
    json_fields=set([]),
    datetime_fields=set(['created_at']),
    sequence_fields={},
    update_cache=('antinuke_settings_cache', ['guild_id']),
    delete_cache=('antinuke_settings_cache', ['guild_id']),
)

async def create_table():
    return await _store.prepare()

async def insert(

    id:int=None,
    guild_id:int=None,
    enabled:bool=None,
    type:str=None,
    bypass_role_id:int=None,
    anti_channel_create:bool=None,
    anti_channel_create_limit:int=None,
    anti_channel_create_punishment:str=None,
    anti_channel_delete:bool=None,
    anti_channel_delete_limit:int=None,
    anti_channel_delete_punishment:str=None,
    anti_channel_update:bool=None,
    anti_channel_update_limit:int=None,
    anti_channel_update_punishment:str=None,
    anti_role_create:bool=None,
    anti_role_create_limit:int=None,
    anti_role_create_punishment:str=None,
    anti_role_delete:bool=None,
    anti_role_delete_limit:int=None,
    anti_role_delete_punishment:str=None,
    anti_role_update:bool=None,
    anti_role_update_limit:int=None,
    anti_role_update_punishment:str=None,
    anti_member_ban:bool=None,
    anti_member_ban_limit:int=None,
    anti_member_ban_punishment:str=None,
    anti_member_unban:bool=None,
    anti_member_unban_limit:int=None,
    anti_member_unban_punishment:str=None,
    anti_member_kick:bool=None,
    anti_member_kick_limit:int=None,
    anti_member_kick_punishment:str=None,
    anti_member_update:bool=None,
    anti_member_update_limit:int=None,
    anti_member_update_punishment:str=None,
    anti_bot_add:bool=None,
    anti_bot_add_limit:int=None,
    anti_bot_add_punishment:str=None,
    anti_invite_delete:bool=None,
    anti_invite_delete_limit:int=None,
    anti_invite_delete_punishment:str=None,
    anti_webhook_create:bool=None,
    anti_webhook_create_limit:int=None,
    anti_webhook_create_punishment:str=None,
    anti_webhook_delete:bool=None,
    anti_webhook_delete_limit:int=None,
    anti_webhook_delete_punishment:str=None,
    anti_webhook_update:bool=None,
    anti_webhook_update_limit:int=None,
    anti_webhook_update_punishment:str=None,
    anti_server_update:bool=None,
    anti_server_update_limit:int=None,
    anti_server_update_punishment:str=None,
    anti_emote_create:bool=None,
    anti_emote_create_limit:int=None,
    anti_emote_create_punishment:str=None,
    anti_emote_delete:bool=None,
    anti_emote_delete_limit:int=None,
    anti_emote_delete_punishment:str=None,
    anti_emote_update:bool=None,
    anti_emote_update_limit:int=None,
    anti_emote_update_punishment:str=None,
    anti_prune_member:bool=None,
    anti_prune_member_limit:int=None,
    anti_prune_member_punishment:str=None,
    anti_everyone_mention:bool=None,
    anti_everyone_mention_limit:int=None,
    anti_everyone_mention_punishment:str=None,
    created_at:str=None
):
    return await _store.insert(locals())

async def update(

    id:int,
    guild_id:int=None,
    enabled:bool=None,
    type:str=None,
    bypass_role_id:int=None,
    anti_channel_create:bool=None,
    anti_channel_create_limit:int=None,
    anti_channel_create_punishment:str=None,
    anti_channel_delete:bool=None,
    anti_channel_delete_limit:int=None,
    anti_channel_delete_punishment:str=None,
    anti_channel_update:bool=None,
    anti_channel_update_limit:int=None,
    anti_channel_update_punishment:str=None,
    anti_role_create:bool=None,
    anti_role_create_limit:int=None,
    anti_role_create_punishment:str=None,
    anti_role_delete:bool=None,
    anti_role_delete_limit:int=None,
    anti_role_delete_punishment:str=None,
    anti_role_update:bool=None,
    anti_role_update_limit:int=None,
    anti_role_update_punishment:str=None,
    anti_member_ban:bool=None,
    anti_member_ban_limit:int=None,
    anti_member_ban_punishment:str=None,
    anti_member_unban:bool=None,
    anti_member_unban_limit:int=None,
    anti_member_unban_punishment:str=None,
    anti_member_kick:bool=None,
    anti_member_kick_limit:int=None,
    anti_member_kick_punishment:str=None,
    anti_member_update:bool=None,
    anti_member_update_limit:int=None,
    anti_member_update_punishment:str=None,
    anti_bot_add:bool=None,
    anti_bot_add_limit:int=None,
    anti_bot_add_punishment:str=None,
    anti_invite_delete:bool=None,
    anti_invite_delete_limit:int=None,
    anti_invite_delete_punishment:str=None,
    anti_webhook_create:bool=None,
    anti_webhook_create_limit:int=None,
    anti_webhook_create_punishment:str=None,
    anti_webhook_delete:bool=None,
    anti_webhook_delete_limit:int=None,
    anti_webhook_delete_punishment:str=None,
    anti_webhook_update:bool=None,
    anti_webhook_update_limit:int=None,
    anti_webhook_update_punishment:str=None,
    anti_server_update:bool=None,
    anti_server_update_limit:int=None,
    anti_server_update_punishment:str=None,
    anti_emote_create:bool=None,
    anti_emote_create_limit:int=None,
    anti_emote_create_punishment:str=None,
    anti_emote_delete:bool=None,
    anti_emote_delete_limit:int=None,
    anti_emote_delete_punishment:str=None,
    anti_emote_update:bool=None,
    anti_emote_update_limit:int=None,
    anti_emote_update_punishment:str=None,
    anti_prune_member:bool=None,
    anti_prune_member_limit:int=None,
    anti_prune_member_punishment:str=None,
    anti_everyone_mention:bool=None,
    anti_everyone_mention_limit:int=None,
    anti_everyone_mention_punishment:str=None,
    created_at:str=None
):
    return await _store.update(locals())

async def get(

    id:int=None,
    guild_id:int=None,
    enabled:bool=None,
    type:str=None,
    bypass_role_id:int=None,
    anti_channel_create:bool=None,
    anti_channel_create_limit:int=None,
    anti_channel_create_punishment:str=None,
    anti_channel_delete:bool=None,
    anti_channel_delete_limit:int=None,
    anti_channel_delete_punishment:str=None,
    anti_channel_update:bool=None,
    anti_channel_update_limit:int=None,
    anti_channel_update_punishment:str=None,
    anti_role_create:bool=None,
    anti_role_create_limit:int=None,
    anti_role_create_punishment:str=None,
    anti_role_delete:bool=None,
    anti_role_delete_limit:int=None,
    anti_role_delete_punishment:str=None,
    anti_role_update:bool=None,
    anti_role_update_limit:int=None,
    anti_role_update_punishment:str=None,
    anti_member_ban:bool=None,
    anti_member_ban_limit:int=None,
    anti_member_ban_punishment:str=None,
    anti_member_unban:bool=None,
    anti_member_unban_limit:int=None,
    anti_member_unban_punishment:str=None,
    anti_member_kick:bool=None,
    anti_member_kick_limit:int=None,
    anti_member_kick_punishment:str=None,
    anti_member_update:bool=None,
    anti_member_update_limit:int=None,
    anti_member_update_punishment:str=None,
    anti_bot_add:bool=None,
    anti_bot_add_limit:int=None,
    anti_bot_add_punishment:str=None,
    anti_invite_delete:bool=None,
    anti_invite_delete_limit:int=None,
    anti_invite_delete_punishment:str=None,
    anti_webhook_create:bool=None,
    anti_webhook_create_limit:int=None,
    anti_webhook_create_punishment:str=None,
    anti_webhook_delete:bool=None,
    anti_webhook_delete_limit:int=None,
    anti_webhook_delete_punishment:str=None,
    anti_webhook_update:bool=None,
    anti_webhook_update_limit:int=None,
    anti_webhook_update_punishment:str=None,
    anti_server_update:bool=None,
    anti_server_update_limit:int=None,
    anti_server_update_punishment:str=None,
    anti_emote_create:bool=None,
    anti_emote_create_limit:int=None,
    anti_emote_create_punishment:str=None,
    anti_emote_delete:bool=None,
    anti_emote_delete_limit:int=None,
    anti_emote_delete_punishment:str=None,
    anti_emote_update:bool=None,
    anti_emote_update_limit:int=None,
    anti_emote_update_punishment:str=None,
    anti_prune_member:bool=None,
    anti_prune_member_limit:int=None,
    anti_prune_member_punishment:str=None,
    anti_everyone_mention:bool=None,
    anti_everyone_mention_limit:int=None,
    anti_everyone_mention_punishment:str=None,
    created_at:str=None
):
    return await _store.get(locals())

async def gets(

    id:int=None,
    guild_id:int=None,
    enabled:bool=None,
    type:str=None,
    bypass_role_id:int=None,
    anti_channel_create:bool=None,
    anti_channel_create_limit:int=None,
    anti_channel_create_punishment:str=None,
    anti_channel_delete:bool=None,
    anti_channel_delete_limit:int=None,
    anti_channel_delete_punishment:str=None,
    anti_channel_update:bool=None,
    anti_channel_update_limit:int=None,
    anti_channel_update_punishment:str=None,
    anti_role_create:bool=None,
    anti_role_create_limit:int=None,
    anti_role_create_punishment:str=None,
    anti_role_delete:bool=None,
    anti_role_delete_limit:int=None,
    anti_role_delete_punishment:str=None,
    anti_role_update:bool=None,
    anti_role_update_limit:int=None,
    anti_role_update_punishment:str=None,
    anti_member_ban:bool=None,
    anti_member_ban_limit:int=None,
    anti_member_ban_punishment:str=None,
    anti_member_unban:bool=None,
    anti_member_unban_limit:int=None,
    anti_member_unban_punishment:str=None,
    anti_member_kick:bool=None,
    anti_member_kick_limit:int=None,
    anti_member_kick_punishment:str=None,
    anti_member_update:bool=None,
    anti_member_update_limit:int=None,
    anti_member_update_punishment:str=None,
    anti_bot_add:bool=None,
    anti_bot_add_limit:int=None,
    anti_bot_add_punishment:str=None,
    anti_invite_delete:bool=None,
    anti_invite_delete_limit:int=None,
    anti_invite_delete_punishment:str=None,
    anti_webhook_create:bool=None,
    anti_webhook_create_limit:int=None,
    anti_webhook_create_punishment:str=None,
    anti_webhook_delete:bool=None,
    anti_webhook_delete_limit:int=None,
    anti_webhook_delete_punishment:str=None,
    anti_webhook_update:bool=None,
    anti_webhook_update_limit:int=None,
    anti_webhook_update_punishment:str=None,
    anti_server_update:bool=None,
    anti_server_update_limit:int=None,
    anti_server_update_punishment:str=None,
    anti_emote_create:bool=None,
    anti_emote_create_limit:int=None,
    anti_emote_create_punishment:str=None,
    anti_emote_delete:bool=None,
    anti_emote_delete_limit:int=None,
    anti_emote_delete_punishment:str=None,
    anti_emote_update:bool=None,
    anti_emote_update_limit:int=None,
    anti_emote_update_punishment:str=None,
    anti_prune_member:bool=None,
    anti_prune_member_limit:int=None,
    anti_prune_member_punishment:str=None,
    anti_everyone_mention:bool=None,
    anti_everyone_mention_limit:int=None,
    anti_everyone_mention_punishment:str=None,
    created_at:str=None
):
    return await _store.gets(locals())

async def delete(

    id:int=None,
    guild_id:int=None,
    enabled:bool=None,
    type:str=None,
    bypass_role_id:int=None,
    anti_channel_create:bool=None,
    anti_channel_create_limit:int=None,
    anti_channel_create_punishment:str=None,
    anti_channel_delete:bool=None,
    anti_channel_delete_limit:int=None,
    anti_channel_delete_punishment:str=None,
    anti_channel_update:bool=None,
    anti_channel_update_limit:int=None,
    anti_channel_update_punishment:str=None,
    anti_role_create:bool=None,
    anti_role_create_limit:int=None,
    anti_role_create_punishment:str=None,
    anti_role_delete:bool=None,
    anti_role_delete_limit:int=None,
    anti_role_delete_punishment:str=None,
    anti_role_update:bool=None,
    anti_role_update_limit:int=None,
    anti_role_update_punishment:str=None,
    anti_member_ban:bool=None,
    anti_member_ban_limit:int=None,
    anti_member_ban_punishment:str=None,
    anti_member_unban:bool=None,
    anti_member_unban_limit:int=None,
    anti_member_unban_punishment:str=None,
    anti_member_kick:bool=None,
    anti_member_kick_limit:int=None,
    anti_member_kick_punishment:str=None,
    anti_member_update:bool=None,
    anti_member_update_limit:int=None,
    anti_member_update_punishment:str=None,
    anti_bot_add:bool=None,
    anti_bot_add_limit:int=None,
    anti_bot_add_punishment:str=None,
    anti_invite_delete:bool=None,
    anti_invite_delete_limit:int=None,
    anti_invite_delete_punishment:str=None,
    anti_webhook_create:bool=None,
    anti_webhook_create_limit:int=None,
    anti_webhook_create_punishment:str=None,
    anti_webhook_delete:bool=None,
    anti_webhook_delete_limit:int=None,
    anti_webhook_delete_punishment:str=None,
    anti_webhook_update:bool=None,
    anti_webhook_update_limit:int=None,
    anti_webhook_update_punishment:str=None,
    anti_server_update:bool=None,
    anti_server_update_limit:int=None,
    anti_server_update_punishment:str=None,
    anti_emote_create:bool=None,
    anti_emote_create_limit:int=None,
    anti_emote_create_punishment:str=None,
    anti_emote_delete:bool=None,
    anti_emote_delete_limit:int=None,
    anti_emote_delete_punishment:str=None,
    anti_emote_update:bool=None,
    anti_emote_update_limit:int=None,
    anti_emote_update_punishment:str=None,
    anti_prune_member:bool=None,
    anti_prune_member_limit:int=None,
    anti_prune_member_punishment:str=None,
    anti_everyone_mention:bool=None,
    anti_everyone_mention_limit:int=None,
    anti_everyone_mention_punishment:str=None,
    created_at:str=None
):
    return await _store.delete(locals())

async def get_all():
    return await _store.get_all()

async def change_antinuke_settings_type(cache_antinuke_settings:dict,new_type:str):
    new_type = new_type.lower()
    if new_type not in ['normal','extream','custom']:
        return logger.warning(f"Invalid type {new_type} is choosen by the user for the guild {cache_antinuke_settings.get('guild_id')}")
    if new_type == 'custom':
        return logger.info(f"Custom settings is choosen by the user.")
    if new_type == 'normal':
        await update(
            id=cache_antinuke_settings.get('id'),

            anti_channel_create=True,
            anti_channel_create_limit=3,
            anti_channel_create_punishment="kick",

            anti_channel_delete=True,
            anti_channel_delete_limit=3,
            anti_channel_delete_punishment="kick",

            anti_channel_update=True,
            anti_channel_update_limit=3,
            anti_channel_update_punishment="kick",

            anti_role_create=True,
            anti_role_create_limit=3,
            anti_role_create_punishment="kick",

            anti_role_delete=True,
            anti_role_delete_limit=3,
            anti_role_delete_punishment="kick",

            anti_role_update=True,
            anti_role_update_limit=3,
            anti_role_update_punishment="kick",

            anti_member_ban=True,
            anti_member_ban_limit=3,
            anti_member_ban_punishment="kick",

            anti_member_unban=True,
            anti_member_unban_limit=3,
            anti_member_unban_punishment="kick",

            anti_member_kick=True,
            anti_member_kick_limit=3,
            anti_member_kick_punishment="kick",

            anti_member_update=True,
            anti_member_update_limit=3,
            anti_member_update_punishment="kick",

            anti_bot_add=True,
            anti_bot_add_limit=2,
            anti_bot_add_punishment="kick",

            anti_invite_delete=True,
            anti_invite_delete_limit=3,
            anti_invite_delete_punishment="kick",

            anti_webhook_create=True,
            anti_webhook_create_limit=3,
            anti_webhook_create_punishment="kick",

            anti_webhook_update=True,
            anti_webhook_update_limit=3,
            anti_webhook_update_punishment="kick",

            anti_server_update=True,
            anti_server_update_limit=3,
            anti_server_update_punishment="kick",

            anti_emote_create=True,
            anti_emote_create_limit=3,
            anti_emote_create_punishment="kick",

            anti_emote_delete=True,
            anti_emote_delete_limit=3,
            anti_emote_delete_punishment="kick",

            anti_emote_update=True,
            anti_emote_update_limit=3,
            anti_emote_update_punishment="kick",

            anti_prune_member=True,
            anti_prune_member_limit=3,
            anti_prune_member_punishment="kick",

            anti_everyone_mention=True,
            anti_everyone_mention_limit=1,
            anti_everyone_mention_punishment="mute"
        )
        return logger.info(f"Normal settings is choosen by the user for the guild {cache_antinuke_settings.get('guild_id')}")
    if new_type == 'extream':
        # all limit will be 1 and puishment will be ban
        await update(
            id=cache_antinuke_settings.get('id'),

            anti_channel_create=True,
            anti_channel_create_limit=1,
            anti_channel_create_punishment="ban",

            anti_channel_delete=True,
            anti_channel_delete_limit=1,
            anti_channel_delete_punishment="ban",

            anti_channel_update=True,
            anti_channel_update_limit=1,
            anti_channel_update_punishment="ban",

            anti_role_create=True,
            anti_role_create_limit=1,
            anti_role_create_punishment="ban",

            anti_role_delete=True,
            anti_role_delete_limit=1,
            anti_role_delete_punishment="ban",

            anti_role_update=True,
            anti_role_update_limit=1,
            anti_role_update_punishment="ban",

            anti_member_ban=True,
            anti_member_ban_limit=1,
            anti_member_ban_punishment="ban",

            anti_member_unban=True,
            anti_member_unban_limit=1,
            anti_member_unban_punishment="ban",

            anti_member_kick=True,
            anti_member_kick_limit=1,
            anti_member_kick_punishment="ban",

            anti_member_update=True,
            anti_member_update_limit=1,
            anti_member_update_punishment="ban",

            anti_bot_add=True,
            anti_bot_add_limit=1,
            anti_bot_add_punishment="ban",

            anti_invite_delete=True,
            anti_invite_delete_limit=1,
            anti_invite_delete_punishment="ban",

            anti_webhook_create=True,
            anti_webhook_create_limit=1,
            anti_webhook_create_punishment="ban",

            anti_webhook_update=True,
            anti_webhook_update_limit=1,
            anti_webhook_update_punishment="ban",

            anti_server_update=True,
            anti_server_update_limit=1,
            anti_server_update_punishment="ban",

            anti_emote_create=True,
            anti_emote_create_limit=1,
            anti_emote_create_punishment="ban",

            anti_emote_delete=True,
            anti_emote_delete_limit=1,
            anti_emote_delete_punishment="ban",

            anti_emote_update=True,
            anti_emote_update_limit=1,
            anti_emote_update_punishment="ban",

            anti_prune_member=True,
            anti_prune_member_limit=1,
            anti_prune_member_punishment="ban",

            anti_everyone_mention=True,
            anti_everyone_mention_limit=1,
            anti_everyone_mention_punishment="kick"
        )
        return logger.info(f"Extream settings is choosen by the user for the guild {cache_antinuke_settings.get('guild_id')}")
